set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

set -g @open 'x'
set -g @open-editor 'C-x'
set -g prefix 'C-z'
set -s extended-keys on
set -as terminal-features "wezterm:extkeys"

# Set theme
set -g @theme_variation 'night'
set -g @theme_plugins 'datetime,weather,playerctl,yay'
set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'

# Rebind pane navigation to vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind [
bind - copy-mode
unbind p
bind [ previous-window
unbind n
bind ] next-window

# Kill pane without confirmation
bind x kill-pane
bind q kill-window

# Rebind split window
bind s split-window -v
bind v split-window -h

bind , resize-pane -x 33%
bind . resize-pane -x 50%
bind / resize-pane -x 66%

# Resize panes
bind Left resize-pane -L 10
bind Right resize-pane -R 10
bind Up resize-pane -U 10
bind Down resize-pane -D 10

# No delay for escape key press
set -sg escape-time 0

# Focus events
set -g focus-events on

# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded."

# Turn on mouse moude
set -g mouse on

set -ga terminal-overrides ",wezterm*:Tc"
set -g default-terminal "xterm-256color"
set -ag terminal-features "xterm-256color:extkeys:kG"

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'
TMUX_FZF_LAUNCH_KEY=f

run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'
