format = """
[░▒▓](#a3aed2)\
[$os](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
${custom.directory}\
[](fg:#769ff0 bg:#394260)\
${custom.fig}\
${custom.git_branch}\
[](fg:#394260 bg:#212736)\
[](fg:#212736 bg:#1d2230)\
[ ](fg:#1d2230)\
$character"""

[custom.directory]
command = """ echo $(pwd) | rev | cut -d "/" -f 4- --complement | rev """
when = """ true """
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $output ]($style)"

[os]
format = "$symbol"
disabled = false

[os.symbols]
Macos = " "

[custom.git_branch]
command = """ echo "$(git symbolic-ref --short HEAD)" """
when = """ [[ ! "$(pwd)" =~ "/google/src/cloud/$USER" ]] && [[ $(git rev-parse --is-inside-work-tree) ]] """
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $output ](fg:#769ff0 bg:#394260)]($style)'

[custom.fig]
command = """ echo "$(pwd)" | cut -d "/" -f 6 """
when = """ [[ "$(pwd)" =~ "/google/src/cloud/$USER" ]] """
style = "bg:#394260"
format = "[ 🌱 ($output) ]($style)"

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[lua]
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[c]
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

